# Generated by Django 3.2.5 on 2021-08-23 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.ImageField(blank=True, null=True, upload_to='documents/%y/%m/%d/')),
                ('licence', models.ImageField(blank=True, null=True, upload_to='documents/%y/%m/%d/')),
                ('card_face', models.ImageField(blank=True, null=True, upload_to='documents/%y/%m/%d/')),
                ('card_back', models.ImageField(blank=True, null=True, upload_to='documents/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('phone', models.CharField(max_length=8, unique=True)),
                ('date_of_Birth', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=4)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.document')),
            ],
        ),
    ]
